### PR TITLE
fix #4

### LINKED ISSUE #4: GHC segfaults (aka "The perils of using a non memory safe language")
https://github.com/esoeylemez/foreign-store/blob/7a64d862908549fd1dd8db8d46849c3984e59309/cbits/store.c#L32

I think this should be 

```
memset(values + size,0,(new_size - size)*sizeof(void*)); 
```

Otherwise not everything is initialised to NULL.

### PR DESCRIPTION
**Pull request by johannesgerer**
fixes #4

### CODE REVIEW

**Review by chrisdone — APPROVED** [review]
Makes sense to me! Good catch!

**Comment by johannesgerer** [comment]
Any chance this could be merged and released on Hackage?

**Comment by chrisdone** [comment]
I don't want to step on the maintainer's toes, but it seems that @esoeylemez has not been active since 2018, so hopefully they won't mind if I merge this and push to Hackage.

**Comment by chrisdone** [comment]
Pushed to Hackage as 0.2.1.

**Pull request merged**
